services:
  - type: web
    name: OpenManus
    runtime: docker
    repo: https://github.com/stepbrotherbaghirov/OpenManus 
    plan: free  # Убедитесь, что план "free"
    envVars:
      - key: OPENAI_API_KEY
        value: "YOUR_API_KEY"
      - key: PORT
        value: "8000"
    region: oregon  # Регион с лучшей производительностью для Free Tier
    dockerContext: .
    dockerfilePath: ./Dockerfile
    autoDeployTrigger: commit
version: "1"
