services:
  - type: web
    name: OpenManus
    runtime: docker
    repo: https://github.com/stepbrotherbaghirov/OpenManus 
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        value: "YOUR_API_KEY"  # Или оставьте пустым и добавьте через интерфейс
      - key: PORT
        value: "8000"  # Стандартный порт для Render
    region: oregon
    dockerContext: .
    dockerfilePath: ./Dockerfile
    autoDeployTrigger: commit
version: "1"
